#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

# on: [push]

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - run: mkdir gh-pages
    - run: touch gh-pages/.nojekyll
    - run: echo "<3" > gh-pages/index.html

    - name: validate JSON
      run: python -c 'import json; f = open("addresslookup/json/addresses.json"); json.load(f)'
    - run: mkdir gh-pages/addresslookup
    - run: cp -r addresslookup/json gh-pages/addresslookup/

    - name: Publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: gh-pages # The folder the action should deploy.
